name: FeatureDiscovery-v1
description: A Bayesian feature regression model with unknown noise precision
author: Lazy Dynamics
roles:
  - user

arguments:
  - name: functions
    description: |
      The functions to use for feature discovery.
      This should be an array of strings.
      The available options are: 
        - "linear"
        - "quadratic"
        - "pairwise"
        - "triplewise"

      The functions can be combined with modifiers, for example "triplewise:tanh" or "pairwise:sigmoid".
      If modifier is not provided, the function is applied as is.

      The available modifiers are:
        - "tanh"
        - "abs"
        - "sigmoid"
        
    type: array
    required: true
    default: 
      - "linear"
      - "quadratic"
      - "pairwise"
      - "triplewise"
  - name: number_of_iterations
    description: The number of variational inference iterations
    type: int
    required: false
    default: 25
  - name: compute_free_energy
    description: Whether to compute the free energy
    type: bool
    required: false
    default: false

parameters:
  - name: omega_mean
    description: The posterior mean of the coefficients parameter `omega`
  - name: omega_covariance
    description: The posterior covariance of the coefficients parameter `omega`
  - name: s_shape
    description: The posterior shape parameter of the noise precision `s` for the likelihood
  - name: s_rate
    description: The posterior rate parameter of the noise precision `s` for the likelihood

data:
  - name: x
    description: |
      Input features for feature discovery.
      This should be an array of numbers. 
      For example, if you have D features, `x` should be an array of D numbers.
    type: array
    required: true
  - name: y
    description: |
      Target values (dependent variables) for the feature discovery regression.
      This is the output variable that the model will attempt to predict
      based on the input features `x` using Bayesian regression. Can be omitted
      if the model is used for inference only.
    type: number
    required: false
