# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ModelInstanceParameters

    ModelInstanceParameters(;
        parameters=nothing,
    )

    - parameters::Dict{String, Any} : An object containing the current parameters of the model instance. The keys are the parameter names as defined in the model configuration, and the values are the parameter values. 
"""
Base.@kwdef mutable struct ModelInstanceParameters <: OpenAPI.APIModel
    parameters::Union{Nothing, Dict{String, Any}} = nothing

    function ModelInstanceParameters(parameters, )
        o = new(parameters, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ModelInstanceParameters

const _property_types_ModelInstanceParameters = Dict{Symbol,String}(Symbol("parameters")=>"Dict{String, Any}", )
OpenAPI.property_type(::Type{ ModelInstanceParameters }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ModelInstanceParameters[name]))}

function OpenAPI.check_required(o::ModelInstanceParameters)
    o.parameters === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::ModelInstanceParameters)
    OpenAPI.validate_property(ModelInstanceParameters, Symbol("parameters"), o.parameters)
end

function OpenAPI.validate_property(::Type{ ModelInstanceParameters }, name::Symbol, val)

end
