services:

  # Swagger UI for viewing OpenAPI specifications
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./openapi:/openapi
    environment:
      SWAGGER_JSON: "/openapi/spec.yaml"
      
  # MongoDB Atlas Local 
  database:
    image: mongodb/mongodb-atlas-local
    ports:
      - "27017:27017"
    environment:
      - MONGODB_INITDB_DATABASE=rxinferserver