services:
  # RxInferServer - Julia API server for RxInfer
  rxinfer-server-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - RXINFER_SERVER_PORT=8000
      - RXINFER_SERVER_DEV_TOKEN=dev-token

  # Swagger UI for viewing OpenAPI specifications
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./openapi:/openapi
    environment:
      SWAGGER_JSON: "/openapi/spec.yaml"