openapi: 3.0.0
info:
  title: RxInferServer API
  description: API for RxInferServer.jl - A Julia server for RxInfer probabilistic programming framework
  version: 1.0.0
  contact:
    name: RxInferServer Team
servers:
  - url: 'http://localhost:8000/v1'
    description: Local development server
paths:
  /info:
    get:
      summary: Get server information
      operationId: getServerInfo
      description: Returns information about the server, including the RxInfer version
      responses:
        '200':
          description: Successfully retrieved server information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerInfo'
components:
  schemas:
    ServerInfo:
      type: object
      required:
        - rxinfer_version
        - server_version
      properties:
        rxinfer_version:
          type: string
          description: The version of RxInfer that the server is using
        server_version:
          type: string
          description: The version of the RxInferServer
        julia_version:
          type: string
          description: The version of Julia 