name = "RxInferClientOpenAPI"
uuid = "8b1d2e5c-3735-4918-bca0-1c0cc8ef920a"
authors = ["Lazy Dynamics <info@lazydynamics.com> and contributors"]
version = "1.0.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
OpenAPI = "d5e62ea6-ddf3-4d43-8e4c-ad5e6c8bfd7d"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"
