# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""InferResponse

    InferResponse(;
        results=nothing,
        errors=nothing,
    )

    - results::Dict{String, Any} : Model-specific results of the inference
    - errors::Vector{ErrorResponse} : List of errors that occurred during the inference call, but were not fatal and the inference was still completed successfully
"""
Base.@kwdef mutable struct InferResponse <: OpenAPI.APIModel
    results::Union{Nothing, Dict{String, Any}} = nothing
    errors::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{ErrorResponse} }

    function InferResponse(results, errors, )
        OpenAPI.validate_property(InferResponse, Symbol("results"), results)
        OpenAPI.validate_property(InferResponse, Symbol("errors"), errors)
        return new(results, errors, )
    end
end # type InferResponse

const _property_types_InferResponse = Dict{Symbol,String}(Symbol("results")=>"Dict{String, Any}", Symbol("errors")=>"Vector{ErrorResponse}", )
OpenAPI.property_type(::Type{ InferResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_InferResponse[name]))}

function check_required(o::InferResponse)
    o.results === nothing && (return false)
    o.errors === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ InferResponse }, name::Symbol, val)


end
