# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""LightweightModelDetails

    LightweightModelDetails(;
        name=nothing,
        description=nothing,
    )

    - name::String : Name of the model (including version identifier, e.g. \&quot;CoinToss-v1\&quot;)
    - description::String : Brief description of the model
"""
Base.@kwdef mutable struct LightweightModelDetails <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing

    function LightweightModelDetails(name, description, )
        OpenAPI.validate_property(LightweightModelDetails, Symbol("name"), name)
        OpenAPI.validate_property(LightweightModelDetails, Symbol("description"), description)
        return new(name, description, )
    end
end # type LightweightModelDetails

const _property_types_LightweightModelDetails = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("description")=>"String", )
OpenAPI.property_type(::Type{ LightweightModelDetails }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_LightweightModelDetails[name]))}

function check_required(o::LightweightModelDetails)
    o.name === nothing && (return false)
    o.description === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ LightweightModelDetails }, name::Symbol, val)


end
