# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ModelInfo

    ModelInfo(;
        info=nothing,
    )

    - info::LightweightModelInfo
"""
Base.@kwdef mutable struct ModelInfo <: OpenAPI.APIModel
    info = nothing # spec type: Union{ Nothing, LightweightModelInfo }

    function ModelInfo(info, )
        OpenAPI.validate_property(ModelInfo, Symbol("info"), info)
        return new(info, )
    end
end # type ModelInfo

const _property_types_ModelInfo = Dict{Symbol,String}(Symbol("info")=>"LightweightModelInfo", )
OpenAPI.property_type(::Type{ ModelInfo }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ModelInfo[name]))}

function check_required(o::ModelInfo)
    o.info === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ModelInfo }, name::Symbol, val)

end
