# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ModelState

    ModelState(;
        state=nothing,
    )

    - state::Dict{String, Any} : Model-specific state
"""
Base.@kwdef mutable struct ModelState <: OpenAPI.APIModel
    state::Union{Nothing, Dict{String, Any}} = nothing

    function ModelState(state, )
        OpenAPI.validate_property(ModelState, Symbol("state"), state)
        return new(state, )
    end
end # type ModelState

const _property_types_ModelState = Dict{Symbol,String}(Symbol("state")=>"Dict{String, Any}", )
OpenAPI.property_type(::Type{ ModelState }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ModelState[name]))}

function check_required(o::ModelState)
    o.state === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ModelState }, name::Symbol, val)

end
