# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreatedModelInstanceState

    CreatedModelInstanceState(;
        state=nothing,
    )

    - state::Dict{String, Any} : An object containing the current state of the model instance.  May include arbitrary fields specific to the model. See the model documentation for more details. 
"""
Base.@kwdef mutable struct CreatedModelInstanceState <: OpenAPI.APIModel
    state::Union{Nothing, Dict{String, Any}} = nothing

    function CreatedModelInstanceState(state, )
        OpenAPI.validate_property(CreatedModelInstanceState, Symbol("state"), state)
        return new(state, )
    end
end # type CreatedModelInstanceState

const _property_types_CreatedModelInstanceState = Dict{Symbol,String}(Symbol("state")=>"Dict{String, Any}", )
OpenAPI.property_type(::Type{ CreatedModelInstanceState }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreatedModelInstanceState[name]))}

function check_required(o::CreatedModelInstanceState)
    o.state === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ CreatedModelInstanceState }, name::Symbol, val)

end
