# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

@doc raw"""TokenResponse

    TokenResponse(;
        token=nothing,
    )

    - token::String : The token to use in the Authorization header with the format \&quot;Bearer {token}\&quot;
"""
Base.@kwdef mutable struct TokenResponse <: OpenAPI.APIModel
    token::Union{Nothing, String} = nothing

    function TokenResponse(token)
        OpenAPI.validate_property(TokenResponse, Symbol("token"), token)
        return new(token)
    end
end # type TokenResponse

const _property_types_TokenResponse = Dict{Symbol, String}(Symbol("token") => "String")
OpenAPI.property_type(::Type{TokenResponse}, name::Symbol) = Union{Nothing, eval(Base.Meta.parse(_property_types_TokenResponse[name]))}

function check_required(o::TokenResponse)
    o.token === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{TokenResponse}, name::Symbol, val) end
