# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PlanningResponse

    PlanningResponse(;
        event_id=nothing,
        results=nothing,
        errors=nothing,
    )

    - event_id::Int64 : Unique identifier for the planning event
    - results::Dict{String, Any} : Model-specific results of the planning
    - errors::Vector{ErrorResponse} : List of errors that occurred during the planning call, but were not fatal and the planning was still completed successfully
"""
Base.@kwdef mutable struct PlanningResponse <: OpenAPI.APIModel
    event_id::Union{Nothing, Int64} = nothing
    results::Union{Nothing, Dict{String, Any}} = nothing
    errors::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{ErrorResponse} }

    function PlanningResponse(event_id, results, errors, )
        OpenAPI.validate_property(PlanningResponse, Symbol("event_id"), event_id)
        OpenAPI.validate_property(PlanningResponse, Symbol("results"), results)
        OpenAPI.validate_property(PlanningResponse, Symbol("errors"), errors)
        return new(event_id, results, errors, )
    end
end # type PlanningResponse

const _property_types_PlanningResponse = Dict{Symbol,String}(Symbol("event_id")=>"Int64", Symbol("results")=>"Dict{String, Any}", Symbol("errors")=>"Vector{ErrorResponse}", )
OpenAPI.property_type(::Type{ PlanningResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PlanningResponse[name]))}

function check_required(o::PlanningResponse)
    o.event_id === nothing && (return false)
    o.results === nothing && (return false)
    o.errors === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ PlanningResponse }, name::Symbol, val)

    if name === Symbol("event_id")
        OpenAPI.validate_param(name, "PlanningResponse", :format, val, "int64")
    end


end
