# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

@doc raw"""UnauthorizedResponse

    UnauthorizedResponse(;
        error="Unauthorized",
        message="The request requires authentication, generate a token using the /token endpoint",
    )

    - error::String : Error message explaining the authentication failure
    - message::String : Additional message explaining the authentication failure
"""
Base.@kwdef mutable struct UnauthorizedResponse <: OpenAPI.APIModel
    error::Union{Nothing, String} = "Unauthorized"
    message::Union{Nothing, String} = "The request requires authentication, generate a token using the /token endpoint"

    function UnauthorizedResponse(error, message)
        OpenAPI.validate_property(UnauthorizedResponse, Symbol("error"), error)
        OpenAPI.validate_property(UnauthorizedResponse, Symbol("message"), message)
        return new(error, message)
    end
end # type UnauthorizedResponse

const _property_types_UnauthorizedResponse = Dict{Symbol, String}(Symbol("error") => "String", Symbol("message") => "String")
OpenAPI.property_type(::Type{UnauthorizedResponse}, name::Symbol) = Union{Nothing, eval(Base.Meta.parse(_property_types_UnauthorizedResponse[name]))}

function check_required(o::UnauthorizedResponse)
    o.error === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{UnauthorizedResponse}, name::Symbol, val)
end
