# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TokenGenerateResponse

    TokenGenerateResponse(;
        token=nothing,
    )

    - token::String : The token to use in the Authorization header with the format \&quot;Bearer {token}\&quot;
"""
Base.@kwdef mutable struct TokenGenerateResponse <: OpenAPI.APIModel
    token::Union{Nothing, String} = nothing

    function TokenGenerateResponse(token, )
        o = new(token, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type TokenGenerateResponse

const _property_types_TokenGenerateResponse = Dict{Symbol,String}(Symbol("token")=>"String", )
OpenAPI.property_type(::Type{ TokenGenerateResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TokenGenerateResponse[name]))}

function OpenAPI.check_required(o::TokenGenerateResponse)
    o.token === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::TokenGenerateResponse)
    OpenAPI.validate_property(TokenGenerateResponse, Symbol("token"), o.token)
end

function OpenAPI.validate_property(::Type{ TokenGenerateResponse }, name::Symbol, val)

end
