# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""NotFoundResponse

    NotFoundResponse(;
        error=nothing,
        message=nothing,
    )

    - error::String : Error type, always \&quot;Not Found\&quot; for this error
    - message::String : Detailed message explaining why the resource was not found
"""
Base.@kwdef mutable struct NotFoundResponse <: OpenAPI.APIModel
    error::Union{Nothing, String} = nothing
    message::Union{Nothing, String} = nothing

    function NotFoundResponse(error, message, )
        OpenAPI.validate_property(NotFoundResponse, Symbol("error"), error)
        OpenAPI.validate_property(NotFoundResponse, Symbol("message"), message)
        return new(error, message, )
    end
end # type NotFoundResponse

const _property_types_NotFoundResponse = Dict{Symbol,String}(Symbol("error")=>"String", Symbol("message")=>"String", )
OpenAPI.property_type(::Type{ NotFoundResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_NotFoundResponse[name]))}

function check_required(o::NotFoundResponse)
    o.error === nothing && (return false)
    o.message === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ NotFoundResponse }, name::Symbol, val)

    if name === Symbol("error")
        OpenAPI.validate_param(name, "NotFoundResponse", :enum, val, ["Not Found"])
    end


end
