# coding: utf-8

"""
    RxInferServer OpenAPI specification

    API for RxInferServer.jl - A Julia server for RxInfer probabilistic programming framework

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from RxInferClientOpenAPI.api.models_api import ModelsApi


class TestModelsApi(unittest.TestCase):
    """ModelsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ModelsApi()

    def tearDown(self) -> None:
        pass

    def test_attach_metadata_to_event(self) -> None:
        """Test case for attach_metadata_to_event

        Attach metadata to an event
        """
        pass

    def test_create_episode(self) -> None:
        """Test case for create_episode

        Create a new episode for a model
        """
        pass

    def test_create_model(self) -> None:
        """Test case for create_model

        Create a new model instance
        """
        pass

    def test_delete_episode(self) -> None:
        """Test case for delete_episode

        Delete an episode for a model
        """
        pass

    def test_delete_model(self) -> None:
        """Test case for delete_model

        Delete a model instance
        """
        pass

    def test_get_created_models_info(self) -> None:
        """Test case for get_created_models_info

        Get information about all created models for a specific token
        """
        pass

    def test_get_episode_info(self) -> None:
        """Test case for get_episode_info

        Get episode information
        """
        pass

    def test_get_episodes(self) -> None:
        """Test case for get_episodes

        Get all episodes for a model
        """
        pass

    def test_get_model_details(self) -> None:
        """Test case for get_model_details

        Get model details
        """
        pass

    def test_get_model_info(self) -> None:
        """Test case for get_model_info

        Get model information
        """
        pass

    def test_get_model_state(self) -> None:
        """Test case for get_model_state

        Get the state of a model
        """
        pass

    def test_get_models(self) -> None:
        """Test case for get_models

        Get models
        """
        pass

    def test_run_inference(self) -> None:
        """Test case for run_inference

        Run inference on a model
        """
        pass

    def test_run_learning(self) -> None:
        """Test case for run_learning

        Learn from previous observations
        """
        pass

    def test_wipe_episode(self) -> None:
        """Test case for wipe_episode

        Wipe all events from an episode
        """
        pass


if __name__ == '__main__':
    unittest.main()
