# coding: utf-8

"""
    RxInferServer OpenAPI specification

    API for RxInferServer.jl - A Julia server for RxInfer probabilistic programming framework

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from RxInferClientOpenAPI.models.model_list import ModelList

class TestModelList(unittest.TestCase):
    """ModelList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelList:
        """Test ModelList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelList`
        """
        model = ModelList()
        if include_optional:
            return ModelList(
                models = [
                    RxInferClientOpenAPI.models.lightweight_model_details.LightweightModelDetails(
                        name = '', 
                        description = '', )
                    ]
            )
        else:
            return ModelList(
                models = [
                    RxInferClientOpenAPI.models.lightweight_model_details.LightweightModelDetails(
                        name = '', 
                        description = '', )
                    ],
        )
        """

    def testModelList(self):
        """Test ModelList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
