# coding: utf-8

"""
    RxInferServer OpenAPI specification

    API for RxInferServer.jl - A Julia server for RxInfer probabilistic programming framework

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from RxInferClientOpenAPI.models.act_request import ActRequest

class TestActRequest(unittest.TestCase):
    """ActRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActRequest:
        """Test ActRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActRequest`
        """
        model = ActRequest()
        if include_optional:
            return ActRequest(
                data = { },
                timestamp = '2024-03-20T12:00Z',
                episode_name = 'default'
            )
        else:
            return ActRequest(
                data = { },
        )
        """

    def testActRequest(self):
        """Test ActRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
