# coding: utf-8

"""
    RxInferServer OpenAPI specification

    API for RxInferServer.jl - A Julia server for RxInfer probabilistic programming framework

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from RxInferClientOpenAPI.models.created_model_info import CreatedModelInfo

class TestCreatedModelInfo(unittest.TestCase):
    """CreatedModelInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatedModelInfo:
        """Test CreatedModelInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatedModelInfo`
        """
        model = CreatedModelInfo()
        if include_optional:
            return CreatedModelInfo(
                model_id = '',
                model_name = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                description = '',
                arguments = { },
                current_episode = 'default'
            )
        else:
            return CreatedModelInfo(
                model_id = '',
                model_name = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                description = '',
                arguments = { },
                current_episode = 'default',
        )
        """

    def testCreatedModelInfo(self):
        """Test CreatedModelInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
