# coding: utf-8

"""
    RxInferServer OpenAPI specification

    API for RxInferServer.jl - A Julia server for RxInfer probabilistic programming framework

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from RxInferClientOpenAPI.models.lightweight_model_details import LightweightModelDetails

class TestLightweightModelDetails(unittest.TestCase):
    """LightweightModelDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LightweightModelDetails:
        """Test LightweightModelDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LightweightModelDetails`
        """
        model = LightweightModelDetails()
        if include_optional:
            return LightweightModelDetails(
                name = '',
                description = ''
            )
        else:
            return LightweightModelDetails(
                name = '',
                description = '',
        )
        """

    def testLightweightModelDetails(self):
        """Test LightweightModelDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
