# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

module RxInferClientOpenAPI

using Dates, TimeZones
using OpenAPI
using OpenAPI.Clients

const API_VERSION = "1.0.0"

include("modelincludes.jl")

include("apis/api_AuthenticationApi.jl")
include("apis/api_ServerApi.jl")

end # module RxInferClientOpenAPI
