# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ModelInstanceState

    ModelInstanceState(;
        state=nothing,
    )

    - state::Dict{String, Any} : An object containing the current state of the model instance.  May include arbitrary fields specific to the model. See the model documentation for more details. 
"""
Base.@kwdef mutable struct ModelInstanceState <: OpenAPI.APIModel
    state::Union{Nothing, Dict{String, Any}} = nothing

    function ModelInstanceState(state, )
        OpenAPI.validate_property(ModelInstanceState, Symbol("state"), state)
        return new(state, )
    end
end # type ModelInstanceState

const _property_types_ModelInstanceState = Dict{Symbol,String}(Symbol("state")=>"Dict{String, Any}", )
OpenAPI.property_type(::Type{ ModelInstanceState }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ModelInstanceState[name]))}

function check_required(o::ModelInstanceState)
    o.state === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ModelInstanceState }, name::Symbol, val)

end
