# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""DeleteModelRequest

    DeleteModelRequest(;
        model_id=nothing,
    )

    - model_id::String : ID of the model to delete
"""
Base.@kwdef mutable struct DeleteModelRequest <: OpenAPI.APIModel
    model_id::Union{Nothing, String} = nothing

    function DeleteModelRequest(model_id, )
        OpenAPI.validate_property(DeleteModelRequest, Symbol("model_id"), model_id)
        return new(model_id, )
    end
end # type DeleteModelRequest

const _property_types_DeleteModelRequest = Dict{Symbol,String}(Symbol("model_id")=>"String", )
OpenAPI.property_type(::Type{ DeleteModelRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DeleteModelRequest[name]))}

function check_required(o::DeleteModelRequest)
    o.model_id === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ DeleteModelRequest }, name::Symbol, val)

    if name === Symbol("model_id")
        OpenAPI.validate_param(name, "DeleteModelRequest", :format, val, "uuid")
    end
end
