# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreateModelResponse

    CreateModelResponse(;
        model_id=nothing,
    )

    - model_id::String : Unique identifier for the created model instance
"""
Base.@kwdef mutable struct CreateModelResponse <: OpenAPI.APIModel
    model_id::Union{Nothing, String} = nothing

    function CreateModelResponse(model_id, )
        OpenAPI.validate_property(CreateModelResponse, Symbol("model_id"), model_id)
        return new(model_id, )
    end
end # type CreateModelResponse

const _property_types_CreateModelResponse = Dict{Symbol,String}(Symbol("model_id")=>"String", )
OpenAPI.property_type(::Type{ CreateModelResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreateModelResponse[name]))}

function check_required(o::CreateModelResponse)
    o.model_id === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ CreateModelResponse }, name::Symbol, val)

    if name === Symbol("model_id")
        OpenAPI.validate_param(name, "CreateModelResponse", :format, val, "uuid")
    end
end
