# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ErrorResponse

    ErrorResponse(;
        error=nothing,
        message=nothing,
    )

    - error::String : Error message explaining the failure
    - message::String : Additional message providing details about the failure
"""
Base.@kwdef mutable struct ErrorResponse <: OpenAPI.APIModel
    error::Union{Nothing, String} = nothing
    message::Union{Nothing, String} = nothing

    function ErrorResponse(error, message, )
        o = new(error, message, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ErrorResponse

const _property_types_ErrorResponse = Dict{Symbol,String}(Symbol("error")=>"String", Symbol("message")=>"String", )
OpenAPI.property_type(::Type{ ErrorResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ErrorResponse[name]))}

function OpenAPI.check_required(o::ErrorResponse)
    o.error === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::ErrorResponse)
    OpenAPI.validate_property(ErrorResponse, Symbol("error"), o.error)
    OpenAPI.validate_property(ErrorResponse, Symbol("message"), o.message)
end

function OpenAPI.validate_property(::Type{ ErrorResponse }, name::Symbol, val)


end
