# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PlanningRequest

    PlanningRequest(;
        data=nothing,
        timestamp=nothing,
        episode_name="default",
    )

    - data::Dict{String, Any} : Model-specific data to run planning on
    - timestamp::ZonedDateTime : Timestamp of the planning request, used to mark the event in the episode
    - episode_name::String : Name of the episode to run planning on
"""
Base.@kwdef mutable struct PlanningRequest <: OpenAPI.APIModel
    data::Union{Nothing, Dict{String, Any}} = nothing
    timestamp::Union{Nothing, ZonedDateTime} = nothing
    episode_name::Union{Nothing, String} = "default"

    function PlanningRequest(data, timestamp, episode_name, )
        OpenAPI.validate_property(PlanningRequest, Symbol("data"), data)
        OpenAPI.validate_property(PlanningRequest, Symbol("timestamp"), timestamp)
        OpenAPI.validate_property(PlanningRequest, Symbol("episode_name"), episode_name)
        return new(data, timestamp, episode_name, )
    end
end # type PlanningRequest

const _property_types_PlanningRequest = Dict{Symbol,String}(Symbol("data")=>"Dict{String, Any}", Symbol("timestamp")=>"ZonedDateTime", Symbol("episode_name")=>"String", )
OpenAPI.property_type(::Type{ PlanningRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PlanningRequest[name]))}

function check_required(o::PlanningRequest)
    o.data === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ PlanningRequest }, name::Symbol, val)


    if name === Symbol("timestamp")
        OpenAPI.validate_param(name, "PlanningRequest", :format, val, "date-time")
    end

end
