# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TokenRolesResponse

    TokenRolesResponse(;
        roles=nothing,
    )

    - roles::Vector{String} : List of roles for the token
"""
Base.@kwdef mutable struct TokenRolesResponse <: OpenAPI.APIModel
    roles::Union{Nothing, Vector{String}} = nothing

    function TokenRolesResponse(roles, )
        o = new(roles, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type TokenRolesResponse

const _property_types_TokenRolesResponse = Dict{Symbol,String}(Symbol("roles")=>"Vector{String}", )
OpenAPI.property_type(::Type{ TokenRolesResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TokenRolesResponse[name]))}

function OpenAPI.check_required(o::TokenRolesResponse)
    o.roles === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::TokenRolesResponse)
    OpenAPI.validate_property(TokenRolesResponse, Symbol("roles"), o.roles)
end

function OpenAPI.validate_property(::Type{ TokenRolesResponse }, name::Symbol, val)

end
