# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ModelList

    ModelList(;
        models=nothing,
    )

    - models::Vector{LightweightModelInfo} : List of available models
"""
Base.@kwdef mutable struct ModelList <: OpenAPI.APIModel
    models::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{LightweightModelInfo} }

    function ModelList(models, )
        OpenAPI.validate_property(ModelList, Symbol("models"), models)
        return new(models, )
    end
end # type ModelList

const _property_types_ModelList = Dict{Symbol,String}(Symbol("models")=>"Vector{LightweightModelInfo}", )
OpenAPI.property_type(::Type{ ModelList }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ModelList[name]))}

function check_required(o::ModelList)
    o.models === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ModelList }, name::Symbol, val)

end
