# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""LightweightModelInfo

    LightweightModelInfo(;
        name=nothing,
        version=nothing,
        description=nothing,
    )

    - name::String : Name of the model
    - version::String : Version of the model
    - description::String : Brief description of the model
"""
Base.@kwdef mutable struct LightweightModelInfo <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    version::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing

    function LightweightModelInfo(name, version, description, )
        OpenAPI.validate_property(LightweightModelInfo, Symbol("name"), name)
        OpenAPI.validate_property(LightweightModelInfo, Symbol("version"), version)
        OpenAPI.validate_property(LightweightModelInfo, Symbol("description"), description)
        return new(name, version, description, )
    end
end # type LightweightModelInfo

const _property_types_LightweightModelInfo = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("version")=>"String", Symbol("description")=>"String", )
OpenAPI.property_type(::Type{ LightweightModelInfo }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_LightweightModelInfo[name]))}

function check_required(o::LightweightModelInfo)
    o.name === nothing && (return false)
    o.version === nothing && (return false)
    o.description === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ LightweightModelInfo }, name::Symbol, val)



end
