# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""LearnResponse_learned_parameters_inner

    LearnResponseLearnedParametersInner(;
        name=nothing,
        value=nothing,
    )

    - name::String : Name of the learned parameter
    - value::Dict{String, Any} : Value of the learned parameter
"""
Base.@kwdef mutable struct LearnResponseLearnedParametersInner <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    value::Union{Nothing, Dict{String, Any}} = nothing

    function LearnResponseLearnedParametersInner(name, value, )
        OpenAPI.validate_property(LearnResponseLearnedParametersInner, Symbol("name"), name)
        OpenAPI.validate_property(LearnResponseLearnedParametersInner, Symbol("value"), value)
        return new(name, value, )
    end
end # type LearnResponseLearnedParametersInner

const _property_types_LearnResponseLearnedParametersInner = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("value")=>"Dict{String, Any}", )
OpenAPI.property_type(::Type{ LearnResponseLearnedParametersInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_LearnResponseLearnedParametersInner[name]))}

function check_required(o::LearnResponseLearnedParametersInner)
    o.name === nothing && (return false)
    o.value === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ LearnResponseLearnedParametersInner }, name::Symbol, val)


end
